Final Project - GSS

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [17]:
var_list = ['marital', 'divorce', 'childsinhh', 'childs', 'hompop_exp','rspgndr', 'rprnt18',
'educ', 'degree', 'paeduc', 'maeduc', 'wrkstat', 'sei', 'realrinc', 'realinc', 'rincome',
'babies','preteen','teens','adults','race', 'raceacs1', 'raceacs2', 'raceacs3',
'raceacs16', 'sex', 'sexornt','vaxsafe','covid12','happy','hapmar','hapcohab', 'satfin',
'health', 'stress', 'neisafe','physact', 'instype01', 'partners', 'condom', 'evidu',
 'smokeday', 'arrest', 'trust', 'helpful','joblose', 'jobfind', 'spwrksta', 'cowrksta', 'class',
'polviews', 'reliten', 'pray', 'attend', 'postlife', 'fear','gunlaw', 'satjob'] # List of variables you want to save

output_filename = 'selected_gss_data.csv' # Name of the file you want to save the data to
#
phase = 0 # Starts in write mode; after one iteration of loop, switches to append mode
#
for k in range(3): # for each chunk of the data
    url = 'https://github.com/DS3001/project_gss/raw/main/gss_chunk_' + str(1+k) + '.parquet' # Create url to the chunk to be processed
    print(url) # Check the url is correct
    df = pd.read_parquet(url) # Download this chunk of data
    print(df.head()) # Visually inspect the first few rows
    if phase == 0:
        df.loc[:,var_list].to_csv(output_filename, # specifies target file to save the chunk to
                                mode='w', # control write versus append
                                header=var_list, # variable names
                                index=False) # no row index saved
        phase = 1 # Switch from write mode to append mode
    elif phase == 1 :
        df.loc[:,var_list].to_csv(output_filename, # specifies target file to save the chunk to
                                mode='a', # control write versus append
                                header=None, # variable names
                                index=False) # no row index saved
        phase = 1 # Switch from write mode to append mode


https://github.com/DS3001/project_gss/raw/main/gss_chunk_1.parquet
   year  id            wrkstat  hrs1  hrs2 evwork    occ  prestige  \
0  1972   1  working full time   NaN   NaN    NaN  205.0      50.0   
1  1972   2            retired   NaN   NaN    yes  441.0      45.0   
2  1972   3  working part time   NaN   NaN    NaN  270.0      44.0   
3  1972   4  working full time   NaN   NaN    NaN    1.0      57.0   
4  1972   5      keeping house   NaN   NaN    yes  385.0      40.0   

         wrkslf wrkgovt  ...  agehef12 agehef13 agehef14  hompoph wtssps_nea  \
0  someone else     NaN  ...       NaN      NaN      NaN      NaN        NaN   
1  someone else     NaN  ...       NaN      NaN      NaN      NaN        NaN   
2  someone else     NaN  ...       NaN      NaN      NaN      NaN        NaN   
3  someone else     NaN  ...       NaN      NaN      NaN      NaN        NaN   
4  someone else     NaN  ...       NaN      NaN      NaN      NaN        NaN   

   wtssnrps_nea  wtssps_next wt

In [18]:
gss = pd.read_csv('selected_gss_data.csv')

<ipython-input-18-9e26a9569f66>:1: DtypeWarning: Columns (5,6,21,22,23,24,26,27,28,31,34,35,36,37,38,39,40,41,42,48) have mixed types. Specify dtype option on import or set low_memory=False.
  gss = pd.read_csv('selected_gss_data.csv')


In [19]:
gss.head()

marital divorce  childsinhh  childs  hompop_exp rspgndr rprnt18  \
0  never married     NaN         NaN     0.0         NaN     NaN     NaN   
1        married      no         NaN     5.0         NaN     NaN     NaN   
2        married      no         NaN     4.0         NaN     NaN     NaN   
3        married      no         NaN     0.0         NaN     NaN     NaN   
4        married      no         NaN     2.0         NaN     NaN     NaN   

   educ                 degree  paeduc  ...  cowrksta          class  \
0  16.0             bachelor's    10.0  ...       NaN   middle class   
1  10.0  less than high school     8.0  ...       NaN   middle class   
2  12.0            high school     8.0  ...       NaN  working class   
3  17.0             bachelor's    16.0  ...       NaN   middle class   
4  12.0            high school     8.0  ...       NaN  working class   

   polviews  reliten  pray                      attend  postlife  fear  \
0       NaN      NaN   NaN  about once or twice a year       NaN   NaN   
1       NaN      NaN   NaN                  every week       NaN   NaN   
2       NaN      NaN   NaN          about once a month       NaN   NaN   
3       NaN      NaN   NaN                       never       NaN   NaN   
4       NaN      NaN   NaN                       never       NaN   NaN   

   gunlaw                 satjob  
0   favor  a little dissatisfied  
1   favor                    NaN  
2   favor   moderately satisfied  
3   favor         very satisfied  
4   favor                    NaN  

[5 rows x 58 columns]

In [20]:
gss['divorce'].unique()
# have you ever been divorced

array([nan, 'no', 'yes'], dtype=object)

In [21]:
gss['marital'].unique()
# marital status

array(['never married', 'married', 'divorced', 'widowed', 'separated',
       nan], dtype=object)

In [22]:
gss['childsinhh'].unique()
# number of children in the household

array([nan,  0.,  2.,  1.,  3.,  5.,  6.,  4.,  8.,  7.])

In [23]:
gss['childs'].unique()
# how many children have you ever had?

array([ 0.,  5.,  4.,  2.,  1.,  3.,  6.,  8.,  7., nan])

In [27]:
gss['hompop_exp'].unique()
# total # of people in household
gss = gss.drop(columns='hompop_exp')

In [29]:
gss['rspgndr'].unique()
# how the home/childcare labor is divided by gender

array([nan, 'women and men take equal responsibility',
       'men take much more responsibility',
       'men take somewhat more responsibility',
       'women take somewhat more responsibility',
       'women take much more responsibility'], dtype=object)